### ISSUE TITLE
Don't post instructions about merge conflicts if the author is an org member

### ISSUE THREAD

**Issue by jyn514** [rust-lang/homu#102]
This was introduced in #101 to make it more clear for new contributors. However, it's annoying for existing contributors because the text is much longer. `bors` should only post the help message if the author is not a member of the organization - presumably if you have enough PRs to be an org member, you know how merge conflicts work.

**Comment by camelid** [comment]
Perhaps just skip the instructions on how to do it with rustbot, but keep the rest? I think some people may forget otherwise. It's not a big deal either way though 🤷
